// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: controlPanel.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

import GRPCCore
import GRPCProtobuf

// MARK: - ControlPanelService

/// Namespace containing generated types for the "ControlPanelService" service.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
public enum ControlPanelService: Sendable {
    /// Service descriptor for the "ControlPanelService" service.
    public static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "ControlPanelService")
    /// Namespace for method metadata.
    public enum Method: Sendable {
        /// Namespace for "ManageGPUServer" metadata.
        public enum ManageGPUServer: Sendable {
            /// Request type for "ManageGPUServer".
            public typealias Input = GPUServerRequest
            /// Response type for "ManageGPUServer".
            public typealias Output = GPUServerResponse
            /// Descriptor for "ManageGPUServer".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "ControlPanelService"),
                method: "ManageGPUServer"
            )
        }
        /// Namespace for "UpdateThrottlingConfig" metadata.
        public enum UpdateThrottlingConfig: Sendable {
            /// Request type for "UpdateThrottlingConfig".
            public typealias Input = ThrottlingRequest
            /// Response type for "UpdateThrottlingConfig".
            public typealias Output = ThrottlingResponse
            /// Descriptor for "UpdateThrottlingConfig".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "ControlPanelService"),
                method: "UpdateThrottlingConfig"
            )
        }
        /// Namespace for "UpdatePem" metadata.
        public enum UpdatePem: Sendable {
            /// Request type for "UpdatePem".
            public typealias Input = UpdatePemRequest
            /// Response type for "UpdatePem".
            public typealias Output = UpdatePemResponse
            /// Descriptor for "UpdatePem".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "ControlPanelService"),
                method: "UpdatePem"
            )
        }
        /// Namespace for "UpdateModelList" metadata.
        public enum UpdateModelList: Sendable {
            /// Request type for "UpdateModelList".
            public typealias Input = UpdateModelListRequest
            /// Response type for "UpdateModelList".
            public typealias Output = UpdateModelListResponse
            /// Descriptor for "UpdateModelList".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "ControlPanelService"),
                method: "UpdateModelList"
            )
        }
        /// Namespace for "UpdateSharedSecret" metadata.
        public enum UpdateSharedSecret: Sendable {
            /// Request type for "UpdateSharedSecret".
            public typealias Input = UpdateSharedSecretRequest
            /// Response type for "UpdateSharedSecret".
            public typealias Output = UpdateSharedSecretResponse
            /// Descriptor for "UpdateSharedSecret".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "ControlPanelService"),
                method: "UpdateSharedSecret"
            )
        }
        /// Namespace for "UpdatePrivateKey" metadata.
        public enum UpdatePrivateKey: Sendable {
            /// Request type for "UpdatePrivateKey".
            public typealias Input = UpdatePrivateKeyRequest
            /// Response type for "UpdatePrivateKey".
            public typealias Output = UpdatePrivateKeyResponse
            /// Descriptor for "UpdatePrivateKey".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "ControlPanelService"),
                method: "UpdatePrivateKey"
            )
        }
        /// Namespace for "UpdateComputeUnit" metadata.
        public enum UpdateComputeUnit: Sendable {
            /// Request type for "UpdateComputeUnit".
            public typealias Input = UpdateComputeUnitRequest
            /// Response type for "UpdateComputeUnit".
            public typealias Output = UpdateComputeUnitResponse
            /// Descriptor for "UpdateComputeUnit".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "ControlPanelService"),
                method: "UpdateComputeUnit"
            )
        }
        /// Descriptors for all methods in the "ControlPanelService" service.
        public static let descriptors: [GRPCCore.MethodDescriptor] = [
            ManageGPUServer.descriptor,
            UpdateThrottlingConfig.descriptor,
            UpdatePem.descriptor,
            UpdateModelList.descriptor,
            UpdateSharedSecret.descriptor,
            UpdatePrivateKey.descriptor,
            UpdateComputeUnit.descriptor
        ]
    }
}

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension GRPCCore.ServiceDescriptor {
    /// Service descriptor for the "ControlPanelService" service.
    public static let ControlPanelService = GRPCCore.ServiceDescriptor(fullyQualifiedService: "ControlPanelService")
}

// MARK: ControlPanelService (server)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension ControlPanelService {
    /// Streaming variant of the service protocol for the "ControlPanelService" service.
    ///
    /// This protocol is the lowest-level of the service protocols generated for this service
    /// giving you the most flexibility over the implementation of your service. This comes at
    /// the cost of more verbose and less strict APIs. Each RPC requires you to implement it in
    /// terms of a request stream and response stream. Where only a single request or response
    /// message is expected, you are responsible for enforcing this invariant is maintained.
    ///
    /// Where possible, prefer using the stricter, less-verbose ``ServiceProtocol``
    /// or ``SimpleServiceProtocol`` instead.
    public protocol StreamingServiceProtocol: GRPCCore.RegistrableRPCService {
        /// Handle the "ManageGPUServer" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `GPUServerRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `GPUServerResponse` messages.
        func manageGPUServer(
            request: GRPCCore.StreamingServerRequest<GPUServerRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<GPUServerResponse>

        /// Handle the "UpdateThrottlingConfig" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `ThrottlingRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `ThrottlingResponse` messages.
        func updateThrottlingConfig(
            request: GRPCCore.StreamingServerRequest<ThrottlingRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<ThrottlingResponse>

        /// Handle the "UpdatePem" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `UpdatePemRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `UpdatePemResponse` messages.
        func updatePem(
            request: GRPCCore.StreamingServerRequest<UpdatePemRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<UpdatePemResponse>

        /// Handle the "UpdateModelList" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `UpdateModelListRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `UpdateModelListResponse` messages.
        func updateModelList(
            request: GRPCCore.StreamingServerRequest<UpdateModelListRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<UpdateModelListResponse>

        /// Handle the "UpdateSharedSecret" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `UpdateSharedSecretRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `UpdateSharedSecretResponse` messages.
        func updateSharedSecret(
            request: GRPCCore.StreamingServerRequest<UpdateSharedSecretRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<UpdateSharedSecretResponse>

        /// Handle the "UpdatePrivateKey" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `UpdatePrivateKeyRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `UpdatePrivateKeyResponse` messages.
        func updatePrivateKey(
            request: GRPCCore.StreamingServerRequest<UpdatePrivateKeyRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<UpdatePrivateKeyResponse>

        /// Handle the "UpdateComputeUnit" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `UpdateComputeUnitRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `UpdateComputeUnitResponse` messages.
        func updateComputeUnit(
            request: GRPCCore.StreamingServerRequest<UpdateComputeUnitRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<UpdateComputeUnitResponse>
    }

    /// Service protocol for the "ControlPanelService" service.
    ///
    /// This protocol is higher level than ``StreamingServiceProtocol`` but lower level than
    /// the ``SimpleServiceProtocol``, it provides access to request and response metadata and
    /// trailing response metadata. If you don't need these then consider using
    /// the ``SimpleServiceProtocol``. If you need fine grained control over your RPCs then
    /// use ``StreamingServiceProtocol``.
    public protocol ServiceProtocol: ControlPanelService.StreamingServiceProtocol {
        /// Handle the "ManageGPUServer" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `GPUServerRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `GPUServerResponse` message.
        func manageGPUServer(
            request: GRPCCore.ServerRequest<GPUServerRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<GPUServerResponse>

        /// Handle the "UpdateThrottlingConfig" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `ThrottlingRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `ThrottlingResponse` message.
        func updateThrottlingConfig(
            request: GRPCCore.ServerRequest<ThrottlingRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<ThrottlingResponse>

        /// Handle the "UpdatePem" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `UpdatePemRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `UpdatePemResponse` message.
        func updatePem(
            request: GRPCCore.ServerRequest<UpdatePemRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<UpdatePemResponse>

        /// Handle the "UpdateModelList" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `UpdateModelListRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `UpdateModelListResponse` message.
        func updateModelList(
            request: GRPCCore.ServerRequest<UpdateModelListRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<UpdateModelListResponse>

        /// Handle the "UpdateSharedSecret" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `UpdateSharedSecretRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `UpdateSharedSecretResponse` message.
        func updateSharedSecret(
            request: GRPCCore.ServerRequest<UpdateSharedSecretRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<UpdateSharedSecretResponse>

        /// Handle the "UpdatePrivateKey" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `UpdatePrivateKeyRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `UpdatePrivateKeyResponse` message.
        func updatePrivateKey(
            request: GRPCCore.ServerRequest<UpdatePrivateKeyRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<UpdatePrivateKeyResponse>

        /// Handle the "UpdateComputeUnit" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `UpdateComputeUnitRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `UpdateComputeUnitResponse` message.
        func updateComputeUnit(
            request: GRPCCore.ServerRequest<UpdateComputeUnitRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<UpdateComputeUnitResponse>
    }

    /// Simple service protocol for the "ControlPanelService" service.
    ///
    /// This is the highest level protocol for the service. The API is the easiest to use but
    /// doesn't provide access to request or response metadata. If you need access to these
    /// then use ``ServiceProtocol`` instead.
    public protocol SimpleServiceProtocol: ControlPanelService.ServiceProtocol {
        /// Handle the "ManageGPUServer" method.
        ///
        /// - Parameters:
        ///   - request: A `GPUServerRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `GPUServerResponse` to respond with.
        func manageGPUServer(
            request: GPUServerRequest,
            context: GRPCCore.ServerContext
        ) async throws -> GPUServerResponse

        /// Handle the "UpdateThrottlingConfig" method.
        ///
        /// - Parameters:
        ///   - request: A `ThrottlingRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `ThrottlingResponse` to respond with.
        func updateThrottlingConfig(
            request: ThrottlingRequest,
            context: GRPCCore.ServerContext
        ) async throws -> ThrottlingResponse

        /// Handle the "UpdatePem" method.
        ///
        /// - Parameters:
        ///   - request: A `UpdatePemRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `UpdatePemResponse` to respond with.
        func updatePem(
            request: UpdatePemRequest,
            context: GRPCCore.ServerContext
        ) async throws -> UpdatePemResponse

        /// Handle the "UpdateModelList" method.
        ///
        /// - Parameters:
        ///   - request: A `UpdateModelListRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `UpdateModelListResponse` to respond with.
        func updateModelList(
            request: UpdateModelListRequest,
            context: GRPCCore.ServerContext
        ) async throws -> UpdateModelListResponse

        /// Handle the "UpdateSharedSecret" method.
        ///
        /// - Parameters:
        ///   - request: A `UpdateSharedSecretRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `UpdateSharedSecretResponse` to respond with.
        func updateSharedSecret(
            request: UpdateSharedSecretRequest,
            context: GRPCCore.ServerContext
        ) async throws -> UpdateSharedSecretResponse

        /// Handle the "UpdatePrivateKey" method.
        ///
        /// - Parameters:
        ///   - request: A `UpdatePrivateKeyRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `UpdatePrivateKeyResponse` to respond with.
        func updatePrivateKey(
            request: UpdatePrivateKeyRequest,
            context: GRPCCore.ServerContext
        ) async throws -> UpdatePrivateKeyResponse

        /// Handle the "UpdateComputeUnit" method.
        ///
        /// - Parameters:
        ///   - request: A `UpdateComputeUnitRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `UpdateComputeUnitResponse` to respond with.
        func updateComputeUnit(
            request: UpdateComputeUnitRequest,
            context: GRPCCore.ServerContext
        ) async throws -> UpdateComputeUnitResponse
    }
}

// Default implementation of 'registerMethods(with:)'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension ControlPanelService.StreamingServiceProtocol {
    public func registerMethods<Transport>(with router: inout GRPCCore.RPCRouter<Transport>) where Transport: GRPCCore.ServerTransport {
        router.registerHandler(
            forMethod: ControlPanelService.Method.ManageGPUServer.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<GPUServerRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<GPUServerResponse>(),
            handler: { request, context in
                try await self.manageGPUServer(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: ControlPanelService.Method.UpdateThrottlingConfig.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<ThrottlingRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<ThrottlingResponse>(),
            handler: { request, context in
                try await self.updateThrottlingConfig(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: ControlPanelService.Method.UpdatePem.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<UpdatePemRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<UpdatePemResponse>(),
            handler: { request, context in
                try await self.updatePem(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: ControlPanelService.Method.UpdateModelList.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<UpdateModelListRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<UpdateModelListResponse>(),
            handler: { request, context in
                try await self.updateModelList(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: ControlPanelService.Method.UpdateSharedSecret.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<UpdateSharedSecretRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<UpdateSharedSecretResponse>(),
            handler: { request, context in
                try await self.updateSharedSecret(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: ControlPanelService.Method.UpdatePrivateKey.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<UpdatePrivateKeyRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<UpdatePrivateKeyResponse>(),
            handler: { request, context in
                try await self.updatePrivateKey(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: ControlPanelService.Method.UpdateComputeUnit.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<UpdateComputeUnitRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<UpdateComputeUnitResponse>(),
            handler: { request, context in
                try await self.updateComputeUnit(
                    request: request,
                    context: context
                )
            }
        )
    }
}

// Default implementation of streaming methods from 'StreamingServiceProtocol'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension ControlPanelService.ServiceProtocol {
    public func manageGPUServer(
        request: GRPCCore.StreamingServerRequest<GPUServerRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<GPUServerResponse> {
        let response = try await self.manageGPUServer(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    public func updateThrottlingConfig(
        request: GRPCCore.StreamingServerRequest<ThrottlingRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<ThrottlingResponse> {
        let response = try await self.updateThrottlingConfig(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    public func updatePem(
        request: GRPCCore.StreamingServerRequest<UpdatePemRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<UpdatePemResponse> {
        let response = try await self.updatePem(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    public func updateModelList(
        request: GRPCCore.StreamingServerRequest<UpdateModelListRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<UpdateModelListResponse> {
        let response = try await self.updateModelList(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    public func updateSharedSecret(
        request: GRPCCore.StreamingServerRequest<UpdateSharedSecretRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<UpdateSharedSecretResponse> {
        let response = try await self.updateSharedSecret(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    public func updatePrivateKey(
        request: GRPCCore.StreamingServerRequest<UpdatePrivateKeyRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<UpdatePrivateKeyResponse> {
        let response = try await self.updatePrivateKey(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    public func updateComputeUnit(
        request: GRPCCore.StreamingServerRequest<UpdateComputeUnitRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<UpdateComputeUnitResponse> {
        let response = try await self.updateComputeUnit(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }
}

// Default implementation of methods from 'ServiceProtocol'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension ControlPanelService.SimpleServiceProtocol {
    public func manageGPUServer(
        request: GRPCCore.ServerRequest<GPUServerRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<GPUServerResponse> {
        return GRPCCore.ServerResponse<GPUServerResponse>(
            message: try await self.manageGPUServer(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    public func updateThrottlingConfig(
        request: GRPCCore.ServerRequest<ThrottlingRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<ThrottlingResponse> {
        return GRPCCore.ServerResponse<ThrottlingResponse>(
            message: try await self.updateThrottlingConfig(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    public func updatePem(
        request: GRPCCore.ServerRequest<UpdatePemRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<UpdatePemResponse> {
        return GRPCCore.ServerResponse<UpdatePemResponse>(
            message: try await self.updatePem(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    public func updateModelList(
        request: GRPCCore.ServerRequest<UpdateModelListRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<UpdateModelListResponse> {
        return GRPCCore.ServerResponse<UpdateModelListResponse>(
            message: try await self.updateModelList(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    public func updateSharedSecret(
        request: GRPCCore.ServerRequest<UpdateSharedSecretRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<UpdateSharedSecretResponse> {
        return GRPCCore.ServerResponse<UpdateSharedSecretResponse>(
            message: try await self.updateSharedSecret(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    public func updatePrivateKey(
        request: GRPCCore.ServerRequest<UpdatePrivateKeyRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<UpdatePrivateKeyResponse> {
        return GRPCCore.ServerResponse<UpdatePrivateKeyResponse>(
            message: try await self.updatePrivateKey(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    public func updateComputeUnit(
        request: GRPCCore.ServerRequest<UpdateComputeUnitRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<UpdateComputeUnitResponse> {
        return GRPCCore.ServerResponse<UpdateComputeUnitResponse>(
            message: try await self.updateComputeUnit(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }
}

// MARK: ControlPanelService (client)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension ControlPanelService {
    /// Generated client protocol for the "ControlPanelService" service.
    ///
    /// You don't need to implement this protocol directly, use the generated
    /// implementation, ``Client``.
    public protocol ClientProtocol: Sendable {
        /// Call the "ManageGPUServer" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `GPUServerRequest` message.
        ///   - serializer: A serializer for `GPUServerRequest` messages.
        ///   - deserializer: A deserializer for `GPUServerResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func manageGPUServer<Result>(
            request: GRPCCore.ClientRequest<GPUServerRequest>,
            serializer: some GRPCCore.MessageSerializer<GPUServerRequest>,
            deserializer: some GRPCCore.MessageDeserializer<GPUServerResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<GPUServerResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "UpdateThrottlingConfig" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `ThrottlingRequest` message.
        ///   - serializer: A serializer for `ThrottlingRequest` messages.
        ///   - deserializer: A deserializer for `ThrottlingResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func updateThrottlingConfig<Result>(
            request: GRPCCore.ClientRequest<ThrottlingRequest>,
            serializer: some GRPCCore.MessageSerializer<ThrottlingRequest>,
            deserializer: some GRPCCore.MessageDeserializer<ThrottlingResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<ThrottlingResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "UpdatePem" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `UpdatePemRequest` message.
        ///   - serializer: A serializer for `UpdatePemRequest` messages.
        ///   - deserializer: A deserializer for `UpdatePemResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func updatePem<Result>(
            request: GRPCCore.ClientRequest<UpdatePemRequest>,
            serializer: some GRPCCore.MessageSerializer<UpdatePemRequest>,
            deserializer: some GRPCCore.MessageDeserializer<UpdatePemResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<UpdatePemResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "UpdateModelList" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `UpdateModelListRequest` message.
        ///   - serializer: A serializer for `UpdateModelListRequest` messages.
        ///   - deserializer: A deserializer for `UpdateModelListResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func updateModelList<Result>(
            request: GRPCCore.ClientRequest<UpdateModelListRequest>,
            serializer: some GRPCCore.MessageSerializer<UpdateModelListRequest>,
            deserializer: some GRPCCore.MessageDeserializer<UpdateModelListResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<UpdateModelListResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "UpdateSharedSecret" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `UpdateSharedSecretRequest` message.
        ///   - serializer: A serializer for `UpdateSharedSecretRequest` messages.
        ///   - deserializer: A deserializer for `UpdateSharedSecretResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func updateSharedSecret<Result>(
            request: GRPCCore.ClientRequest<UpdateSharedSecretRequest>,
            serializer: some GRPCCore.MessageSerializer<UpdateSharedSecretRequest>,
            deserializer: some GRPCCore.MessageDeserializer<UpdateSharedSecretResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<UpdateSharedSecretResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "UpdatePrivateKey" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `UpdatePrivateKeyRequest` message.
        ///   - serializer: A serializer for `UpdatePrivateKeyRequest` messages.
        ///   - deserializer: A deserializer for `UpdatePrivateKeyResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func updatePrivateKey<Result>(
            request: GRPCCore.ClientRequest<UpdatePrivateKeyRequest>,
            serializer: some GRPCCore.MessageSerializer<UpdatePrivateKeyRequest>,
            deserializer: some GRPCCore.MessageDeserializer<UpdatePrivateKeyResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<UpdatePrivateKeyResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "UpdateComputeUnit" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `UpdateComputeUnitRequest` message.
        ///   - serializer: A serializer for `UpdateComputeUnitRequest` messages.
        ///   - deserializer: A deserializer for `UpdateComputeUnitResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func updateComputeUnit<Result>(
            request: GRPCCore.ClientRequest<UpdateComputeUnitRequest>,
            serializer: some GRPCCore.MessageSerializer<UpdateComputeUnitRequest>,
            deserializer: some GRPCCore.MessageDeserializer<UpdateComputeUnitResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<UpdateComputeUnitResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable
    }

    /// Generated client for the "ControlPanelService" service.
    ///
    /// The ``Client`` provides an implementation of ``ClientProtocol`` which wraps
    /// a `GRPCCore.GRPCCClient`. The underlying `GRPCClient` provides the long-lived
    /// means of communication with the remote peer.
    public struct Client<Transport>: ClientProtocol where Transport: GRPCCore.ClientTransport {
        private let client: GRPCCore.GRPCClient<Transport>

        /// Creates a new client wrapping the provided `GRPCCore.GRPCClient`.
        ///
        /// - Parameters:
        ///   - client: A `GRPCCore.GRPCClient` providing a communication channel to the service.
        public init(wrapping client: GRPCCore.GRPCClient<Transport>) {
            self.client = client
        }

        /// Call the "ManageGPUServer" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `GPUServerRequest` message.
        ///   - serializer: A serializer for `GPUServerRequest` messages.
        ///   - deserializer: A deserializer for `GPUServerResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func manageGPUServer<Result>(
            request: GRPCCore.ClientRequest<GPUServerRequest>,
            serializer: some GRPCCore.MessageSerializer<GPUServerRequest>,
            deserializer: some GRPCCore.MessageDeserializer<GPUServerResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<GPUServerResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: ControlPanelService.Method.ManageGPUServer.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "UpdateThrottlingConfig" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `ThrottlingRequest` message.
        ///   - serializer: A serializer for `ThrottlingRequest` messages.
        ///   - deserializer: A deserializer for `ThrottlingResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func updateThrottlingConfig<Result>(
            request: GRPCCore.ClientRequest<ThrottlingRequest>,
            serializer: some GRPCCore.MessageSerializer<ThrottlingRequest>,
            deserializer: some GRPCCore.MessageDeserializer<ThrottlingResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<ThrottlingResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: ControlPanelService.Method.UpdateThrottlingConfig.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "UpdatePem" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `UpdatePemRequest` message.
        ///   - serializer: A serializer for `UpdatePemRequest` messages.
        ///   - deserializer: A deserializer for `UpdatePemResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func updatePem<Result>(
            request: GRPCCore.ClientRequest<UpdatePemRequest>,
            serializer: some GRPCCore.MessageSerializer<UpdatePemRequest>,
            deserializer: some GRPCCore.MessageDeserializer<UpdatePemResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<UpdatePemResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: ControlPanelService.Method.UpdatePem.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "UpdateModelList" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `UpdateModelListRequest` message.
        ///   - serializer: A serializer for `UpdateModelListRequest` messages.
        ///   - deserializer: A deserializer for `UpdateModelListResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func updateModelList<Result>(
            request: GRPCCore.ClientRequest<UpdateModelListRequest>,
            serializer: some GRPCCore.MessageSerializer<UpdateModelListRequest>,
            deserializer: some GRPCCore.MessageDeserializer<UpdateModelListResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<UpdateModelListResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: ControlPanelService.Method.UpdateModelList.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "UpdateSharedSecret" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `UpdateSharedSecretRequest` message.
        ///   - serializer: A serializer for `UpdateSharedSecretRequest` messages.
        ///   - deserializer: A deserializer for `UpdateSharedSecretResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func updateSharedSecret<Result>(
            request: GRPCCore.ClientRequest<UpdateSharedSecretRequest>,
            serializer: some GRPCCore.MessageSerializer<UpdateSharedSecretRequest>,
            deserializer: some GRPCCore.MessageDeserializer<UpdateSharedSecretResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<UpdateSharedSecretResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: ControlPanelService.Method.UpdateSharedSecret.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "UpdatePrivateKey" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `UpdatePrivateKeyRequest` message.
        ///   - serializer: A serializer for `UpdatePrivateKeyRequest` messages.
        ///   - deserializer: A deserializer for `UpdatePrivateKeyResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func updatePrivateKey<Result>(
            request: GRPCCore.ClientRequest<UpdatePrivateKeyRequest>,
            serializer: some GRPCCore.MessageSerializer<UpdatePrivateKeyRequest>,
            deserializer: some GRPCCore.MessageDeserializer<UpdatePrivateKeyResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<UpdatePrivateKeyResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: ControlPanelService.Method.UpdatePrivateKey.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "UpdateComputeUnit" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `UpdateComputeUnitRequest` message.
        ///   - serializer: A serializer for `UpdateComputeUnitRequest` messages.
        ///   - deserializer: A deserializer for `UpdateComputeUnitResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func updateComputeUnit<Result>(
            request: GRPCCore.ClientRequest<UpdateComputeUnitRequest>,
            serializer: some GRPCCore.MessageSerializer<UpdateComputeUnitRequest>,
            deserializer: some GRPCCore.MessageDeserializer<UpdateComputeUnitResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<UpdateComputeUnitResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: ControlPanelService.Method.UpdateComputeUnit.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }
    }
}

// Helpers providing default arguments to 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension ControlPanelService.ClientProtocol {
    /// Call the "ManageGPUServer" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `GPUServerRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func manageGPUServer<Result>(
        request: GRPCCore.ClientRequest<GPUServerRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<GPUServerResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.manageGPUServer(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<GPUServerRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<GPUServerResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "UpdateThrottlingConfig" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `ThrottlingRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func updateThrottlingConfig<Result>(
        request: GRPCCore.ClientRequest<ThrottlingRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<ThrottlingResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.updateThrottlingConfig(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<ThrottlingRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<ThrottlingResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "UpdatePem" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `UpdatePemRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func updatePem<Result>(
        request: GRPCCore.ClientRequest<UpdatePemRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<UpdatePemResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.updatePem(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<UpdatePemRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<UpdatePemResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "UpdateModelList" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `UpdateModelListRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func updateModelList<Result>(
        request: GRPCCore.ClientRequest<UpdateModelListRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<UpdateModelListResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.updateModelList(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<UpdateModelListRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<UpdateModelListResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "UpdateSharedSecret" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `UpdateSharedSecretRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func updateSharedSecret<Result>(
        request: GRPCCore.ClientRequest<UpdateSharedSecretRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<UpdateSharedSecretResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.updateSharedSecret(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<UpdateSharedSecretRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<UpdateSharedSecretResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "UpdatePrivateKey" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `UpdatePrivateKeyRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func updatePrivateKey<Result>(
        request: GRPCCore.ClientRequest<UpdatePrivateKeyRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<UpdatePrivateKeyResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.updatePrivateKey(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<UpdatePrivateKeyRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<UpdatePrivateKeyResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "UpdateComputeUnit" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `UpdateComputeUnitRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func updateComputeUnit<Result>(
        request: GRPCCore.ClientRequest<UpdateComputeUnitRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<UpdateComputeUnitResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.updateComputeUnit(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<UpdateComputeUnitRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<UpdateComputeUnitResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }
}

// Helpers providing sugared APIs for 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension ControlPanelService.ClientProtocol {
    /// Call the "ManageGPUServer" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func manageGPUServer<Result>(
        _ message: GPUServerRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<GPUServerResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<GPUServerRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.manageGPUServer(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "UpdateThrottlingConfig" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func updateThrottlingConfig<Result>(
        _ message: ThrottlingRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<ThrottlingResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<ThrottlingRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.updateThrottlingConfig(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "UpdatePem" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func updatePem<Result>(
        _ message: UpdatePemRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<UpdatePemResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<UpdatePemRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.updatePem(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "UpdateModelList" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func updateModelList<Result>(
        _ message: UpdateModelListRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<UpdateModelListResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<UpdateModelListRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.updateModelList(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "UpdateSharedSecret" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func updateSharedSecret<Result>(
        _ message: UpdateSharedSecretRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<UpdateSharedSecretResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<UpdateSharedSecretRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.updateSharedSecret(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "UpdatePrivateKey" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func updatePrivateKey<Result>(
        _ message: UpdatePrivateKeyRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<UpdatePrivateKeyResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<UpdatePrivateKeyRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.updatePrivateKey(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "UpdateComputeUnit" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func updateComputeUnit<Result>(
        _ message: UpdateComputeUnitRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<UpdateComputeUnitResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<UpdateComputeUnitRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.updateComputeUnit(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }
}