// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: imageService.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

import GRPCCore
import GRPCProtobuf

// MARK: - ImageGenerationService

/// Namespace containing generated types for the "ImageGenerationService" service.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
public enum ImageGenerationService: Sendable {
    /// Service descriptor for the "ImageGenerationService" service.
    public static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "ImageGenerationService")
    /// Namespace for method metadata.
    public enum Method: Sendable {
        /// Namespace for "GenerateImage" metadata.
        public enum GenerateImage: Sendable {
            /// Request type for "GenerateImage".
            public typealias Input = ImageGenerationRequest
            /// Response type for "GenerateImage".
            public typealias Output = ImageGenerationResponse
            /// Descriptor for "GenerateImage".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "ImageGenerationService"),
                method: "GenerateImage"
            )
        }
        /// Namespace for "RemoteDownload" metadata.
        public enum RemoteDownload: Sendable {
            /// Request type for "RemoteDownload".
            public typealias Input = RemoteDownloadRequest
            /// Response type for "RemoteDownload".
            public typealias Output = RemoteDownloadResponse
            /// Descriptor for "RemoteDownload".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "ImageGenerationService"),
                method: "RemoteDownload"
            )
        }
        /// Namespace for "FilesExist" metadata.
        public enum FilesExist: Sendable {
            /// Request type for "FilesExist".
            public typealias Input = FileListRequest
            /// Response type for "FilesExist".
            public typealias Output = FileExistenceResponse
            /// Descriptor for "FilesExist".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "ImageGenerationService"),
                method: "FilesExist"
            )
        }
        /// Namespace for "UploadFile" metadata.
        public enum UploadFile: Sendable {
            /// Request type for "UploadFile".
            public typealias Input = FileUploadRequest
            /// Response type for "UploadFile".
            public typealias Output = UploadResponse
            /// Descriptor for "UploadFile".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "ImageGenerationService"),
                method: "UploadFile"
            )
        }
        /// Namespace for "Echo" metadata.
        public enum Echo: Sendable {
            /// Request type for "Echo".
            public typealias Input = EchoRequest
            /// Response type for "Echo".
            public typealias Output = EchoReply
            /// Descriptor for "Echo".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "ImageGenerationService"),
                method: "Echo"
            )
        }
        /// Namespace for "Pubkey" metadata.
        public enum Pubkey: Sendable {
            /// Request type for "Pubkey".
            public typealias Input = PubkeyRequest
            /// Response type for "Pubkey".
            public typealias Output = PubkeyResponse
            /// Descriptor for "Pubkey".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "ImageGenerationService"),
                method: "Pubkey"
            )
        }
        /// Namespace for "Hours" metadata.
        public enum Hours: Sendable {
            /// Request type for "Hours".
            public typealias Input = HoursRequest
            /// Response type for "Hours".
            public typealias Output = HoursResponse
            /// Descriptor for "Hours".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "ImageGenerationService"),
                method: "Hours"
            )
        }
        /// Descriptors for all methods in the "ImageGenerationService" service.
        public static let descriptors: [GRPCCore.MethodDescriptor] = [
            GenerateImage.descriptor,
            RemoteDownload.descriptor,
            FilesExist.descriptor,
            UploadFile.descriptor,
            Echo.descriptor,
            Pubkey.descriptor,
            Hours.descriptor
        ]
    }
}

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension GRPCCore.ServiceDescriptor {
    /// Service descriptor for the "ImageGenerationService" service.
    public static let ImageGenerationService = GRPCCore.ServiceDescriptor(fullyQualifiedService: "ImageGenerationService")
}

// MARK: ImageGenerationService (server)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension ImageGenerationService {
    /// Streaming variant of the service protocol for the "ImageGenerationService" service.
    ///
    /// This protocol is the lowest-level of the service protocols generated for this service
    /// giving you the most flexibility over the implementation of your service. This comes at
    /// the cost of more verbose and less strict APIs. Each RPC requires you to implement it in
    /// terms of a request stream and response stream. Where only a single request or response
    /// message is expected, you are responsible for enforcing this invariant is maintained.
    ///
    /// Where possible, prefer using the stricter, less-verbose ``ServiceProtocol``
    /// or ``SimpleServiceProtocol`` instead.
    public protocol StreamingServiceProtocol: GRPCCore.RegistrableRPCService {
        /// Handle the "GenerateImage" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `ImageGenerationRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `ImageGenerationResponse` messages.
        func generateImage(
            request: GRPCCore.StreamingServerRequest<ImageGenerationRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<ImageGenerationResponse>

        /// Handle the "RemoteDownload" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `RemoteDownloadRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `RemoteDownloadResponse` messages.
        func remoteDownload(
            request: GRPCCore.StreamingServerRequest<RemoteDownloadRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<RemoteDownloadResponse>

        /// Handle the "FilesExist" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `FileListRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `FileExistenceResponse` messages.
        func filesExist(
            request: GRPCCore.StreamingServerRequest<FileListRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<FileExistenceResponse>

        /// Handle the "UploadFile" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `FileUploadRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `UploadResponse` messages.
        func uploadFile(
            request: GRPCCore.StreamingServerRequest<FileUploadRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<UploadResponse>

        /// Handle the "Echo" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `EchoRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `EchoReply` messages.
        func echo(
            request: GRPCCore.StreamingServerRequest<EchoRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<EchoReply>

        /// Handle the "Pubkey" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `PubkeyRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `PubkeyResponse` messages.
        func pubkey(
            request: GRPCCore.StreamingServerRequest<PubkeyRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<PubkeyResponse>

        /// Handle the "Hours" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `HoursRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `HoursResponse` messages.
        func hours(
            request: GRPCCore.StreamingServerRequest<HoursRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<HoursResponse>
    }

    /// Service protocol for the "ImageGenerationService" service.
    ///
    /// This protocol is higher level than ``StreamingServiceProtocol`` but lower level than
    /// the ``SimpleServiceProtocol``, it provides access to request and response metadata and
    /// trailing response metadata. If you don't need these then consider using
    /// the ``SimpleServiceProtocol``. If you need fine grained control over your RPCs then
    /// use ``StreamingServiceProtocol``.
    public protocol ServiceProtocol: ImageGenerationService.StreamingServiceProtocol {
        /// Handle the "GenerateImage" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `ImageGenerationRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `ImageGenerationResponse` messages.
        func generateImage(
            request: GRPCCore.ServerRequest<ImageGenerationRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<ImageGenerationResponse>

        /// Handle the "RemoteDownload" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `RemoteDownloadRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `RemoteDownloadResponse` messages.
        func remoteDownload(
            request: GRPCCore.ServerRequest<RemoteDownloadRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<RemoteDownloadResponse>

        /// Handle the "FilesExist" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `FileListRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `FileExistenceResponse` message.
        func filesExist(
            request: GRPCCore.ServerRequest<FileListRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<FileExistenceResponse>

        /// Handle the "UploadFile" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `FileUploadRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `UploadResponse` messages.
        func uploadFile(
            request: GRPCCore.StreamingServerRequest<FileUploadRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<UploadResponse>

        /// Handle the "Echo" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `EchoRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `EchoReply` message.
        func echo(
            request: GRPCCore.ServerRequest<EchoRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<EchoReply>

        /// Handle the "Pubkey" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `PubkeyRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `PubkeyResponse` message.
        func pubkey(
            request: GRPCCore.ServerRequest<PubkeyRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<PubkeyResponse>

        /// Handle the "Hours" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `HoursRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `HoursResponse` message.
        func hours(
            request: GRPCCore.ServerRequest<HoursRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<HoursResponse>
    }

    /// Simple service protocol for the "ImageGenerationService" service.
    ///
    /// This is the highest level protocol for the service. The API is the easiest to use but
    /// doesn't provide access to request or response metadata. If you need access to these
    /// then use ``ServiceProtocol`` instead.
    public protocol SimpleServiceProtocol: ImageGenerationService.ServiceProtocol {
        /// Handle the "GenerateImage" method.
        ///
        /// - Parameters:
        ///   - request: A `ImageGenerationRequest` message.
        ///   - response: A response stream of `ImageGenerationResponse` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        func generateImage(
            request: ImageGenerationRequest,
            response: GRPCCore.RPCWriter<ImageGenerationResponse>,
            context: GRPCCore.ServerContext
        ) async throws

        /// Handle the "RemoteDownload" method.
        ///
        /// - Parameters:
        ///   - request: A `RemoteDownloadRequest` message.
        ///   - response: A response stream of `RemoteDownloadResponse` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        func remoteDownload(
            request: RemoteDownloadRequest,
            response: GRPCCore.RPCWriter<RemoteDownloadResponse>,
            context: GRPCCore.ServerContext
        ) async throws

        /// Handle the "FilesExist" method.
        ///
        /// - Parameters:
        ///   - request: A `FileListRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `FileExistenceResponse` to respond with.
        func filesExist(
            request: FileListRequest,
            context: GRPCCore.ServerContext
        ) async throws -> FileExistenceResponse

        /// Handle the "UploadFile" method.
        ///
        /// - Parameters:
        ///   - request: A stream of `FileUploadRequest` messages.
        ///   - response: A response stream of `UploadResponse` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        func uploadFile(
            request: GRPCCore.RPCAsyncSequence<FileUploadRequest, any Swift.Error>,
            response: GRPCCore.RPCWriter<UploadResponse>,
            context: GRPCCore.ServerContext
        ) async throws

        /// Handle the "Echo" method.
        ///
        /// - Parameters:
        ///   - request: A `EchoRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `EchoReply` to respond with.
        func echo(
            request: EchoRequest,
            context: GRPCCore.ServerContext
        ) async throws -> EchoReply

        /// Handle the "Pubkey" method.
        ///
        /// - Parameters:
        ///   - request: A `PubkeyRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `PubkeyResponse` to respond with.
        func pubkey(
            request: PubkeyRequest,
            context: GRPCCore.ServerContext
        ) async throws -> PubkeyResponse

        /// Handle the "Hours" method.
        ///
        /// - Parameters:
        ///   - request: A `HoursRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `HoursResponse` to respond with.
        func hours(
            request: HoursRequest,
            context: GRPCCore.ServerContext
        ) async throws -> HoursResponse
    }
}

// Default implementation of 'registerMethods(with:)'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension ImageGenerationService.StreamingServiceProtocol {
    public func registerMethods<Transport>(with router: inout GRPCCore.RPCRouter<Transport>) where Transport: GRPCCore.ServerTransport {
        router.registerHandler(
            forMethod: ImageGenerationService.Method.GenerateImage.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<ImageGenerationRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<ImageGenerationResponse>(),
            handler: { request, context in
                try await self.generateImage(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: ImageGenerationService.Method.RemoteDownload.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<RemoteDownloadRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<RemoteDownloadResponse>(),
            handler: { request, context in
                try await self.remoteDownload(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: ImageGenerationService.Method.FilesExist.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<FileListRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<FileExistenceResponse>(),
            handler: { request, context in
                try await self.filesExist(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: ImageGenerationService.Method.UploadFile.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<FileUploadRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<UploadResponse>(),
            handler: { request, context in
                try await self.uploadFile(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: ImageGenerationService.Method.Echo.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<EchoRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<EchoReply>(),
            handler: { request, context in
                try await self.echo(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: ImageGenerationService.Method.Pubkey.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<PubkeyRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<PubkeyResponse>(),
            handler: { request, context in
                try await self.pubkey(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: ImageGenerationService.Method.Hours.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<HoursRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<HoursResponse>(),
            handler: { request, context in
                try await self.hours(
                    request: request,
                    context: context
                )
            }
        )
    }
}

// Default implementation of streaming methods from 'StreamingServiceProtocol'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension ImageGenerationService.ServiceProtocol {
    public func generateImage(
        request: GRPCCore.StreamingServerRequest<ImageGenerationRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<ImageGenerationResponse> {
        let response = try await self.generateImage(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return response
    }

    public func remoteDownload(
        request: GRPCCore.StreamingServerRequest<RemoteDownloadRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<RemoteDownloadResponse> {
        let response = try await self.remoteDownload(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return response
    }

    public func filesExist(
        request: GRPCCore.StreamingServerRequest<FileListRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<FileExistenceResponse> {
        let response = try await self.filesExist(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    public func echo(
        request: GRPCCore.StreamingServerRequest<EchoRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<EchoReply> {
        let response = try await self.echo(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    public func pubkey(
        request: GRPCCore.StreamingServerRequest<PubkeyRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<PubkeyResponse> {
        let response = try await self.pubkey(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    public func hours(
        request: GRPCCore.StreamingServerRequest<HoursRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<HoursResponse> {
        let response = try await self.hours(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }
}

// Default implementation of methods from 'ServiceProtocol'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension ImageGenerationService.SimpleServiceProtocol {
    public func generateImage(
        request: GRPCCore.ServerRequest<ImageGenerationRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<ImageGenerationResponse> {
        return GRPCCore.StreamingServerResponse<ImageGenerationResponse>(
            metadata: [:],
            producer: { writer in
                try await self.generateImage(
                    request: request.message,
                    response: writer,
                    context: context
                )
                return [:]
            }
        )
    }

    public func remoteDownload(
        request: GRPCCore.ServerRequest<RemoteDownloadRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<RemoteDownloadResponse> {
        return GRPCCore.StreamingServerResponse<RemoteDownloadResponse>(
            metadata: [:],
            producer: { writer in
                try await self.remoteDownload(
                    request: request.message,
                    response: writer,
                    context: context
                )
                return [:]
            }
        )
    }

    public func filesExist(
        request: GRPCCore.ServerRequest<FileListRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<FileExistenceResponse> {
        return GRPCCore.ServerResponse<FileExistenceResponse>(
            message: try await self.filesExist(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    public func uploadFile(
        request: GRPCCore.StreamingServerRequest<FileUploadRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<UploadResponse> {
        return GRPCCore.StreamingServerResponse<UploadResponse>(
            metadata: [:],
            producer: { writer in
                try await self.uploadFile(
                    request: request.messages,
                    response: writer,
                    context: context
                )
                return [:]
            }
        )
    }

    public func echo(
        request: GRPCCore.ServerRequest<EchoRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<EchoReply> {
        return GRPCCore.ServerResponse<EchoReply>(
            message: try await self.echo(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    public func pubkey(
        request: GRPCCore.ServerRequest<PubkeyRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<PubkeyResponse> {
        return GRPCCore.ServerResponse<PubkeyResponse>(
            message: try await self.pubkey(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    public func hours(
        request: GRPCCore.ServerRequest<HoursRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<HoursResponse> {
        return GRPCCore.ServerResponse<HoursResponse>(
            message: try await self.hours(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }
}

// MARK: ImageGenerationService (client)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension ImageGenerationService {
    /// Generated client protocol for the "ImageGenerationService" service.
    ///
    /// You don't need to implement this protocol directly, use the generated
    /// implementation, ``Client``.
    public protocol ClientProtocol: Sendable {
        /// Call the "GenerateImage" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `ImageGenerationRequest` message.
        ///   - serializer: A serializer for `ImageGenerationRequest` messages.
        ///   - deserializer: A deserializer for `ImageGenerationResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func generateImage<Result>(
            request: GRPCCore.ClientRequest<ImageGenerationRequest>,
            serializer: some GRPCCore.MessageSerializer<ImageGenerationRequest>,
            deserializer: some GRPCCore.MessageDeserializer<ImageGenerationResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<ImageGenerationResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "RemoteDownload" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `RemoteDownloadRequest` message.
        ///   - serializer: A serializer for `RemoteDownloadRequest` messages.
        ///   - deserializer: A deserializer for `RemoteDownloadResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func remoteDownload<Result>(
            request: GRPCCore.ClientRequest<RemoteDownloadRequest>,
            serializer: some GRPCCore.MessageSerializer<RemoteDownloadRequest>,
            deserializer: some GRPCCore.MessageDeserializer<RemoteDownloadResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<RemoteDownloadResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "FilesExist" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `FileListRequest` message.
        ///   - serializer: A serializer for `FileListRequest` messages.
        ///   - deserializer: A deserializer for `FileExistenceResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func filesExist<Result>(
            request: GRPCCore.ClientRequest<FileListRequest>,
            serializer: some GRPCCore.MessageSerializer<FileListRequest>,
            deserializer: some GRPCCore.MessageDeserializer<FileExistenceResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<FileExistenceResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "UploadFile" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request producing `FileUploadRequest` messages.
        ///   - serializer: A serializer for `FileUploadRequest` messages.
        ///   - deserializer: A deserializer for `UploadResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func uploadFile<Result>(
            request: GRPCCore.StreamingClientRequest<FileUploadRequest>,
            serializer: some GRPCCore.MessageSerializer<FileUploadRequest>,
            deserializer: some GRPCCore.MessageDeserializer<UploadResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<UploadResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "Echo" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `EchoRequest` message.
        ///   - serializer: A serializer for `EchoRequest` messages.
        ///   - deserializer: A deserializer for `EchoReply` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func echo<Result>(
            request: GRPCCore.ClientRequest<EchoRequest>,
            serializer: some GRPCCore.MessageSerializer<EchoRequest>,
            deserializer: some GRPCCore.MessageDeserializer<EchoReply>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<EchoReply>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "Pubkey" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `PubkeyRequest` message.
        ///   - serializer: A serializer for `PubkeyRequest` messages.
        ///   - deserializer: A deserializer for `PubkeyResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func pubkey<Result>(
            request: GRPCCore.ClientRequest<PubkeyRequest>,
            serializer: some GRPCCore.MessageSerializer<PubkeyRequest>,
            deserializer: some GRPCCore.MessageDeserializer<PubkeyResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<PubkeyResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "Hours" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `HoursRequest` message.
        ///   - serializer: A serializer for `HoursRequest` messages.
        ///   - deserializer: A deserializer for `HoursResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func hours<Result>(
            request: GRPCCore.ClientRequest<HoursRequest>,
            serializer: some GRPCCore.MessageSerializer<HoursRequest>,
            deserializer: some GRPCCore.MessageDeserializer<HoursResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<HoursResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable
    }

    /// Generated client for the "ImageGenerationService" service.
    ///
    /// The ``Client`` provides an implementation of ``ClientProtocol`` which wraps
    /// a `GRPCCore.GRPCCClient`. The underlying `GRPCClient` provides the long-lived
    /// means of communication with the remote peer.
    public struct Client<Transport>: ClientProtocol where Transport: GRPCCore.ClientTransport {
        private let client: GRPCCore.GRPCClient<Transport>

        /// Creates a new client wrapping the provided `GRPCCore.GRPCClient`.
        ///
        /// - Parameters:
        ///   - client: A `GRPCCore.GRPCClient` providing a communication channel to the service.
        public init(wrapping client: GRPCCore.GRPCClient<Transport>) {
            self.client = client
        }

        /// Call the "GenerateImage" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `ImageGenerationRequest` message.
        ///   - serializer: A serializer for `ImageGenerationRequest` messages.
        ///   - deserializer: A deserializer for `ImageGenerationResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func generateImage<Result>(
            request: GRPCCore.ClientRequest<ImageGenerationRequest>,
            serializer: some GRPCCore.MessageSerializer<ImageGenerationRequest>,
            deserializer: some GRPCCore.MessageDeserializer<ImageGenerationResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<ImageGenerationResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable {
            try await self.client.serverStreaming(
                request: request,
                descriptor: ImageGenerationService.Method.GenerateImage.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "RemoteDownload" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `RemoteDownloadRequest` message.
        ///   - serializer: A serializer for `RemoteDownloadRequest` messages.
        ///   - deserializer: A deserializer for `RemoteDownloadResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func remoteDownload<Result>(
            request: GRPCCore.ClientRequest<RemoteDownloadRequest>,
            serializer: some GRPCCore.MessageSerializer<RemoteDownloadRequest>,
            deserializer: some GRPCCore.MessageDeserializer<RemoteDownloadResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<RemoteDownloadResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable {
            try await self.client.serverStreaming(
                request: request,
                descriptor: ImageGenerationService.Method.RemoteDownload.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "FilesExist" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `FileListRequest` message.
        ///   - serializer: A serializer for `FileListRequest` messages.
        ///   - deserializer: A deserializer for `FileExistenceResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func filesExist<Result>(
            request: GRPCCore.ClientRequest<FileListRequest>,
            serializer: some GRPCCore.MessageSerializer<FileListRequest>,
            deserializer: some GRPCCore.MessageDeserializer<FileExistenceResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<FileExistenceResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: ImageGenerationService.Method.FilesExist.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "UploadFile" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request producing `FileUploadRequest` messages.
        ///   - serializer: A serializer for `FileUploadRequest` messages.
        ///   - deserializer: A deserializer for `UploadResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func uploadFile<Result>(
            request: GRPCCore.StreamingClientRequest<FileUploadRequest>,
            serializer: some GRPCCore.MessageSerializer<FileUploadRequest>,
            deserializer: some GRPCCore.MessageDeserializer<UploadResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<UploadResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable {
            try await self.client.bidirectionalStreaming(
                request: request,
                descriptor: ImageGenerationService.Method.UploadFile.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "Echo" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `EchoRequest` message.
        ///   - serializer: A serializer for `EchoRequest` messages.
        ///   - deserializer: A deserializer for `EchoReply` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func echo<Result>(
            request: GRPCCore.ClientRequest<EchoRequest>,
            serializer: some GRPCCore.MessageSerializer<EchoRequest>,
            deserializer: some GRPCCore.MessageDeserializer<EchoReply>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<EchoReply>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: ImageGenerationService.Method.Echo.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "Pubkey" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `PubkeyRequest` message.
        ///   - serializer: A serializer for `PubkeyRequest` messages.
        ///   - deserializer: A deserializer for `PubkeyResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func pubkey<Result>(
            request: GRPCCore.ClientRequest<PubkeyRequest>,
            serializer: some GRPCCore.MessageSerializer<PubkeyRequest>,
            deserializer: some GRPCCore.MessageDeserializer<PubkeyResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<PubkeyResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: ImageGenerationService.Method.Pubkey.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "Hours" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `HoursRequest` message.
        ///   - serializer: A serializer for `HoursRequest` messages.
        ///   - deserializer: A deserializer for `HoursResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func hours<Result>(
            request: GRPCCore.ClientRequest<HoursRequest>,
            serializer: some GRPCCore.MessageSerializer<HoursRequest>,
            deserializer: some GRPCCore.MessageDeserializer<HoursResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<HoursResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: ImageGenerationService.Method.Hours.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }
    }
}

// Helpers providing default arguments to 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension ImageGenerationService.ClientProtocol {
    /// Call the "GenerateImage" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `ImageGenerationRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func generateImage<Result>(
        request: GRPCCore.ClientRequest<ImageGenerationRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<ImageGenerationResponse>) async throws -> Result
    ) async throws -> Result where Result: Sendable {
        try await self.generateImage(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<ImageGenerationRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<ImageGenerationResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "RemoteDownload" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `RemoteDownloadRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func remoteDownload<Result>(
        request: GRPCCore.ClientRequest<RemoteDownloadRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<RemoteDownloadResponse>) async throws -> Result
    ) async throws -> Result where Result: Sendable {
        try await self.remoteDownload(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<RemoteDownloadRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<RemoteDownloadResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "FilesExist" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `FileListRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func filesExist<Result>(
        request: GRPCCore.ClientRequest<FileListRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<FileExistenceResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.filesExist(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<FileListRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<FileExistenceResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "UploadFile" method.
    ///
    /// - Parameters:
    ///   - request: A streaming request producing `FileUploadRequest` messages.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func uploadFile<Result>(
        request: GRPCCore.StreamingClientRequest<FileUploadRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<UploadResponse>) async throws -> Result
    ) async throws -> Result where Result: Sendable {
        try await self.uploadFile(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<FileUploadRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<UploadResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "Echo" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `EchoRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func echo<Result>(
        request: GRPCCore.ClientRequest<EchoRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<EchoReply>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.echo(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<EchoRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<EchoReply>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "Pubkey" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `PubkeyRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func pubkey<Result>(
        request: GRPCCore.ClientRequest<PubkeyRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<PubkeyResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.pubkey(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<PubkeyRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<PubkeyResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "Hours" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `HoursRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func hours<Result>(
        request: GRPCCore.ClientRequest<HoursRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<HoursResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.hours(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<HoursRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<HoursResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }
}

// Helpers providing sugared APIs for 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension ImageGenerationService.ClientProtocol {
    /// Call the "GenerateImage" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func generateImage<Result>(
        _ message: ImageGenerationRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<ImageGenerationResponse>) async throws -> Result
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<ImageGenerationRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.generateImage(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "RemoteDownload" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func remoteDownload<Result>(
        _ message: RemoteDownloadRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<RemoteDownloadResponse>) async throws -> Result
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<RemoteDownloadRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.remoteDownload(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "FilesExist" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func filesExist<Result>(
        _ message: FileListRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<FileExistenceResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<FileListRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.filesExist(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "UploadFile" method.
    ///
    /// - Parameters:
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - producer: A closure producing request messages to send to the server. The request
    ///       stream is closed when the closure returns.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func uploadFile<Result>(
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        requestProducer producer: @Sendable @escaping (GRPCCore.RPCWriter<FileUploadRequest>) async throws -> Void,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<UploadResponse>) async throws -> Result
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.StreamingClientRequest<FileUploadRequest>(
            metadata: metadata,
            producer: producer
        )
        return try await self.uploadFile(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "Echo" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func echo<Result>(
        _ message: EchoRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<EchoReply>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<EchoRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.echo(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "Pubkey" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func pubkey<Result>(
        _ message: PubkeyRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<PubkeyResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<PubkeyRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.pubkey(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "Hours" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func hours<Result>(
        _ message: HoursRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<HoursResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<HoursRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.hours(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }
}